language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install enchant

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: python setup.py test

after_success:
  coveralls
